### ISSUE TITLE
What to plot?

### ISSUE THREAD

**Issue by v4hn** [captain-yoshi/moveit_benchmark_suite#16]
There is an exponential number of potential plots to generate from the new default configuration. It does make sense to generate *lots* of them to browse at some point,
but there should be some order among them (important ones first, details later).
I propose to list each plot explicitly in, e.g., `config/plots.yaml`.

- FCL vs Bullet
  - time from collision checks benchmark
  - comparing planning time on the different scenes
  - overall success / correctness metrics (possibly restricted to a few planners)
- MGI vs PP
  - time of RRTConnect over all scenes
- Scenes&goal constraints
  - compare average planning time/success/correctness between scenes (possibly measuring the impact of a complex collision mesh outside the workspace)
- Planners
  - nice plots where the xtics are the planners - somehow aggregating over scenes/ constraints/ configurations...

Best case: all plots can be extended to multiple commits to compare them.

**Comment by captain-yoshi** [comment]
@v4hn For the `Scenes&goal constraints` do we want to plot single/multiple specific planner/s ?
```yaml
html_config:
  # Scenes & goal constraints
  - title: Scenes & goal constraints
    legend_filters:
      - type/MOTION PLANNING PP
      - config/scene/
    xtick_filters:
      - config/planner/RRTConnect
      #- config/planner/BST
      - config/collision_detector/FCL
    metrics:
      - time: boxplot
      - success: boxplot             # will be removed
      - correct: boxplot             # will be removed
      - avg_success: bargraph
      - avg_correct: bargraph
```
I have added the `success` and `avg_success` just as an example. We should only plot success/correctness with bar graphs on aggregated results. Here is the html [file](https://github.com/captain-yoshi/moveit_benchmark_suite/files/7260915/test.zip).
