### ISSUE TITLE
Add ability to add small changes to the profiler config

### ISSUE THREAD

**Issue by captain-yoshi** [captain-yoshi/moveit_benchmark_suite#33]
Add ability to add small changes for profiling for a certain configuration. Instead of having long

In this example, the `profiler_config` would give 2 pair-wise solutions. But with the `extend_config` keyword, one could add small changes to a particular file. The profiler would end up with 5 pair-wise solutions. 

```yaml
profiler_config:
  ...
  motion_plan_requests:
    jc_goal:  package://my_package/request1.yaml
    pose_goal:  package://my_package/request2.yaml
  ...

extend_config:
  motion_plan_requests:
    jc_goal:
      - num_planning_attempts: 2
      - num_planning_attempts: 3
      - num_planning_attempts: 4
      - num_planning_attempts: 7
```
The new motion_plan_requests would be named `jc_goal#1` and so on in the dataset.
**Note:** The original `jc_goal` would be overrided by the extend_conf, and thus give 4 `jc_goal`.  
  
\
Inspiration taken by google's [micro benchmark ](https://github.com/google/benchmark/blob/main/docs/user_guide.md#passing-arguments).
```cpp
BENCHMARK(BM_memcpy)->Arg(8)->Arg(64)->Arg(512);
```

**Comment by captain-yoshi** [comment]
Can create additionnal pair-wise combinations.
E.g, the request `jc_goal` is overriding 4 times and new requests names are automatically
created: `jc_goal_1` to `jc_goal_4`.

```yaml
extend_resources_config:
  requests:
    - name: jc_goal
      resources:
        - num_planning_attempts: 2
        - num_planning_attempts: 3
        - num_planning_attempts: 4
        - num_planning_attempts: 7
  planning_pipelines:
    - name: my_ompl
      resources:
        - panda_arm_hand:
            enforce_joint_model_state_space: false
        - panda_arm_hand:
            enforce_joint_model_state_space: true
  robots:
    name: panda
    resources:
      - kinematics:
          panda_arm:
            kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
            kinematics_solver_search_resolution: 0.005
            kinematics_solver_timeout: 0.05
      - kinematics:
          panda_arm:
            kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
            kinematics_solver_search_resolution: 0.005
            kinematics_solver_timeout: 0.005

```
