### ISSUE TITLE
Resource builder simplification

### ISSUE THREAD

**Issue by captain-yoshi** [captain-yoshi/moveit_benchmark_suite#54]
Add these option fields to make building queries easier. 
- **override**: Override specific resource name (`regex`) with changes. 
- **diff**: Builds new resource from another resource and merge differences.
- **temp**: Sets a resource as temporary, eg. used for constructing a resource but will not count as a final resource.

This will make the `extendRessources` method obsolete and simplify things in the `ResourceBuilder` class. It would be easier to resolve #24, because the profiler config would not be modified in another YAML node.

```yaml
profiler_config:
  # Resource moveit_config (robot)
  robots:
    - name: panda
      temp: ~
      resources:
        urdf: package://moveit_benchmark_suite_resources/robots/panda/urdf/panda.urdf
        srdf: package://moveit_benchmark_suite_resources/robots/panda/config/panda.srdf
        kinematics: package://moveit_benchmark_suite_resources/robots/panda/config/kinematics.yaml
        joint_limits: package://moveit_benchmark_suite_resources/robots/panda/config/joint_limits.yaml
    - name: panda_kdl
      diff: panda
      resource:
        kinematic:
          panda_arm:
            kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
            kinematics_solver_search_resolution: 0.005
            kinematics_solver_timeout: 0.05
    - name: panda_trackik
      diff: panda
      resource:
        kinematics:
          panda_arm:
            kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
            kinematics_solver_search_resolution: 0.005
            kinematics_solver_timeout: 0.005

  # Resource moveit_msgs/MotionPlanRequest
  requests:
    - name: jc
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/jc.yaml
    - name: jc_pcp
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/jc_pcp.yaml
    - override: .*
      resource:
        allowed_planning_time: 5.0
        num_planning_attempts: 1

  # Resource moveit_msgs/PlanningScene
  scenes:
    - name: empty_scene
      resource: package://moveit_benchmark_suite_resources/scenes/empty/empty.urdf.xacro
    - name: primitive_scene
      resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/primitive.urdf.xacro
    # - name: mesh_scene
    #   resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/mesh_16k.urdf.xacro

  collision_detectors:
    - FCL

  # Resource moveit_config (planning pipeline)
  planning_pipelines:
    - name: ompl
      resource: package://moveit_benchmark_suite_resources/robots/panda/config/ompl_planning.yaml
    - override: ompl
      resource:
        - panda_arm_hand:
            enforce_joint_model_state_space: false
    - name: ompl_joint_ss
      diff: ompl
      resource:
        - panda_arm_hand:
             enforce_joint_model_state_space: true
```
