### ISSUE TITLE
Add metric units field in dataset

### ISSUE THREAD

**Issue by captain-yoshi** [captain-yoshi/moveit_benchmark_suite#55]
```yaml
- dataset:
    # Metadata (See full dataset)
    ...

    metric_units:
      time: second
      length: meter    
```
This also could speed up filtering.
