### ISSUE TITLE
Seperate statistics from metrics in a dataset

### ISSUE THREAD

**Issue by captain-yoshi** [captain-yoshi/moveit_benchmark_suite#56]
```yaml
data:
  - query:
       collision_detector: FCL
       pipeline: ompl
       planner: RRTConnect
       request: jc
       robot: panda
       scene: empty_scene
     metrics:
       clearance: [.inf, .inf, .inf, .inf, .inf]
       correct: [1, 1, 1, 1, 1]
       length: [5.5403108999999979, 5.5403109000000006, 5.5403109000000006, 5.5403108999999997, 5.5403109000000015]
       smoothness: [3.5527136983121241e-16, 1.8271098889006922e-15, 2.5376526317334257e-16, 9.1355494941948921e-16, 4.8215400001130992e-16]
       success: [1, 1, 1, 1, 1]
       time: [0.018708215, 0.019656818, 0.019612866, 0.020764061, 0.01635122]
       waypoints: [35, 35, 35, 35, 35]
    statistics:
       correct: {metric: correct, type: mean, N: 60}
```
TODO
- Retrieve the `moveit_benchmark_suite_output` version and add it if different from the the current dataset. 
- Add a statistic_units field ?
- Change configuration for Aggregator and Plotting.
