### ISSUE TITLE
Dataset: YAML representation

### ISSUE THREAD

**Issue by captain-yoshi** [captain-yoshi/moveit_benchmark_suite#62]
Datasets are serialized as a YAML sequence. Instead, we should use the explicit YAML [documents](https://yaml.org/spec/1.2.2/#91-documents):
- Less indentation equals better looking
- Less typing when filtering

Current dataset:
```yaml
- dataset:
    name: mario
    nemesis: bowser
    friends:
      - luigi
      - toad
- dataset:
    name: luigi
    nemesis: king-boo
    friends:
      - mario
      - toad
```

Proposed change:
```yaml
---
name: mario
nemesis: bowser
friends:
  - luigi
  - toad
---
name: luigi
nemesis: king-boo
friends:
  - mario
  - toad
...
```
