### ISSUE TITLE
Validate robot state joint name and positions

### ISSUE THREAD

**Issue by captain-yoshi** [captain-yoshi/moveit_benchmark_suite#84]
This error should be checked when building queries and thus not run the benchmark.

```bash
[ INFO] [1662743272.323767708]: Using planning request adapter 'Fix Start State Path Constraints'
[ERROR] [1662743272.325754167]: Different number of names and positions in JointState message: 9, 7
```

``` yaml
# To reproduce
start_state:
  joint_state:
    header:
      frame_id: panda_link0
    name: [panda_joint1, panda_joint2, panda_joint3, panda_joint4, panda_joint5, panda_joint6, panda_joint7, panda_finger_joint1, panda_finger_joint2]
    position: [0, 0, 0, 0, 0, 1.571, 0.785] # Missing panda finger joint values

```
