### ISSUE TITLE
How to plot

### ISSUE THREAD

**Issue by haryngod** [captain-yoshi/moveit_benchmark_suite#91]
I tried to use plot_dataset.launch.
I executed motion_planning_pp_mesh_quality with [this configuration ](https://drive.google.com/file/d/1wo_FThbmxUeQQSTziw7Rk-kvUpZMkN_R/view?usp=share_link) and I got the [output file](https://drive.google.com/file/d/1fs3c9D1Sp8my9tn7cbkk3jGo-JqsuU6y/view?usp=share_link).
Then I edited [plot yaml ](https://drive.google.com/file/d/1n8_U34VTrMQHXQJCx5SXhu6pbQh1G7fv/view?usp=share_link)file but it still below message and graph is empty.
```bash
[ WARN] [1668515038.106764117]: Plot skipped, dataset is empty after applying filters.
[ WARN] [1668515038.107522849]: Press Ctl-C to terminate GNUPlot
```

Did I miss something?

**Comment by captain-yoshi** [comment]
You are missing the correct name for the request in your dataset (your output file). There is no request named `poc`.

```yaml
gnuplot_config:
  plots:
    # individual requests wrt. scenes, FCL and robot with mesh qualities
    - filters:
        - ns: query/planner
          val: EST
        - ns: query/request
          val: 'jc-blk02'   # you can also test without quotes
```

I think there is currently a limitation with the way the YAML parser handles some strings. Sometimes it quotes a string like it did with your `jc-blk02`.

I will leave this issue open in case you have other questions relating to how to plot.
